name: Scrape and Update Jobs

on:
  schedule:
    - cron: '0 8,13 * * *' # runs at 1pm and 6pm IST (2:30am and 7:30am UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Scrape jobs
        run: python jobscraper.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Github Actions
          author_email: actions@github.com
          message: Update jobs.json
          add: jobs.json
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN}}
